#!/usr/bin/env dash

# Entry point for controlling alises.

. aliases/6080.sh
. aliases/cse.sh
. aliases/git.sh
. aliases/rust.sh
. aliases/scrap-code.sh
. aliases/scripts.sh
. aliases/shell.sh
. aliases/thesis.sh

# cd
alias uhc='cd ~/"OneDrive - UNSW/Documents/UHC"'

# projects
alias prj="cd '$HOME/projects'"
alias mve='prj; cd mve'
