#!/usr/bin/env dash

# Entry point for controlling alises.

. aliases/6080.sh
. aliases/cse.sh
. aliases/git.sh
. aliases/rust.sh
. aliases/scrap-code.sh
. aliases/scripts.sh
. aliases/shell.sh
. aliases/thesis.sh

# cd
alias uhc='cd ~/"OneDrive - UNSW/Documents/UHC"'

# ls 
alias ls='ls -G'
alias l='ls -1'

# open related
alias o='open'
alias go="open -a 'Google Chrome'"

# projects
alias prj="cd '$HOME/projects'"
alias mve='prj; cd mve'

# index
alias index='grep -E "^#"'
